import { Inter } from "next/font/google";
import "./style/globals.css";
import Navbar from "./components/Navbar/page";
import Background from "./components/Background/page";
import Transition from './Transition'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Horizon",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Background />
        <Navbar />
        <Transition>{children}</Transition>
        </body>
    </html>
  );
}
