import { Inter } from "next/font/google";
import "@/style/globals.css";
import "@/style/fonts.css";
import Navbar from "@/components/Navbar/page";
import Background from "@/components/Background/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Horizon",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Background />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
